from django.urls import path

from .secure_views import (
    SecurePdfMergeAsyncView,
    SecurePdfToImagesView,
    SecureProcessingJobDetailView,
    SecureProcessingJobDownloadView,
)
from .views import (
    ImageCompressView,
    ImageConvertView,
    ImageResizeView,
    ImageRotateFlipView,
    ImagesToPdfView,
    PdfAddAttachmentsView,
    PdfAddBlankPageView,
    PdfAlternateMergeView,
    PdfCombineSinglePageView,
    PdfDeletePagesView,
    PdfDividePagesView,
    PdfExtractAttachmentsView,
    PdfExtractPagesView,
    PdfGridCombineView,
    PdfMergeView,
    PdfMultiToolView,
    PdfNUpView,
    PdfOrganizeView,
    PdfPosterizeView,
    PdfReversePagesView,
    PdfRotateCustomView,
    PdfRotateView,
    PdfSplitView,
    ProcessingJobListView,
)
from .views_extra import PdfEditAttachmentsView, PdfToZipView


app_name = "processing"

urlpatterns = [
    path("pdf/merge/", PdfMergeView.as_view(), name="pdf-merge"),
    path("pdf/images-to-pdf/", ImagesToPdfView.as_view(), name="images-to-pdf"),
    path("pdf/split/", PdfSplitView.as_view(), name="pdf-split"),
    path("pdf/delete-pages/", PdfDeletePagesView.as_view(), name="pdf-delete-pages"),
    path("pdf/extract-pages/", PdfExtractPagesView.as_view(), name="pdf-extract-pages"),
    path("pdf/organize/", PdfOrganizeView.as_view(), name="pdf-organize"),
    path("pdf/rotate-custom/", PdfRotateCustomView.as_view(), name="pdf-rotate-custom"),
    path("pdf/add-blank-page/", PdfAddBlankPageView.as_view(), name="pdf-add-blank-page"),
    path("pdf/reverse-pages/", PdfReversePagesView.as_view(), name="pdf-reverse-pages"),
    path("pdf/n-up/", PdfNUpView.as_view(), name="pdf-n-up"),
    path("pdf/grid-combine/", PdfGridCombineView.as_view(), name="pdf-grid-combine"),
    path("pdf/alternate-merge/", PdfAlternateMergeView.as_view(), name="pdf-alternate-merge"),
    path("pdf/divide-pages/", PdfDividePagesView.as_view(), name="pdf-divide-pages"),
    path("pdf/combine-single-page/", PdfCombineSinglePageView.as_view(), name="pdf-combine-single-page"),
    path("pdf/posterize/", PdfPosterizeView.as_view(), name="pdf-posterize"),
    path("pdf/multi-tool/", PdfMultiToolView.as_view(), name="pdf-multi-tool"),
    path("pdf/add-attachments/", PdfAddAttachmentsView.as_view(), name="pdf-add-attachments"),
    path("pdf/extract-attachments/", PdfExtractAttachmentsView.as_view(), name="pdf-extract-attachments"),
    path("pdf/edit-attachments/", PdfEditAttachmentsView.as_view(), name="pdf-edit-attachments"),
    path("pdf/to-zip/", PdfToZipView.as_view(), name="pdf-to-zip"),
    path("pdf/rotate/", PdfRotateView.as_view(), name="pdf-rotate"),
    path("pdf/to-images/", SecurePdfToImagesView.as_view(), name="pdf-to-images"),
    path("pdf/merge/async/", SecurePdfMergeAsyncView.as_view(), name="pdf-merge-async"),
    path("jobs/", ProcessingJobListView.as_view(), name="job-list"),
    path("jobs/<uuid:job_id>/", SecureProcessingJobDetailView.as_view(), name="job-detail"),
    path(
        "jobs/<uuid:job_id>/download/",
        SecureProcessingJobDownloadView.as_view(),
        name="job-download",
    ),
    path("images/convert/", ImageConvertView.as_view(), name="image-convert"),
    path("images/resize/", ImageResizeView.as_view(), name="image-resize"),
    path("images/compress/", ImageCompressView.as_view(), name="image-compress"),
    path("images/rotate-flip/", ImageRotateFlipView.as_view(), name="image-rotate-flip"),
]
