# Generated by Django 6.0.5 on 2026-05-06 15:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tool",
                    models.CharField(
                        choices=[
                            ("PDF_MERGE", "Merge PDF"),
                            ("PDF_SPLIT", "Split PDF"),
                            ("PDF_ROTATE", "Rotate PDF"),
                            ("PDF_TO_IMAGES", "PDF to Images"),
                            ("IMAGE_CONVERT", "Convert Image"),
                            ("IMAGE_RESIZE", "Resize Image"),
                            ("IMAGE_COMPRESS", "Compress Image"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "input_file",
                    models.FileField(
                        blank=True, null=True, upload_to="processing/input/"
                    ),
                ),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to="processing/output/"
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("input_size", models.PositiveBigIntegerField(default=0)),
                ("output_size", models.PositiveBigIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processing_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="processing__user_id_57f414_idx",
                    ),
                    models.Index(
                        fields=["status"], name="processing__status_4baf38_idx"
                    ),
                    models.Index(fields=["tool"], name="processing__tool_754a97_idx"),
                    models.Index(
                        fields=["expires_at"], name="processing__expires_81ca12_idx"
                    ),
                ],
            },
        ),
    ]
