# Generated by Django 6.0.5 on 2026-05-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingjob",
            name="tool",
            field=models.CharField(
                choices=[
                    ("PDF_MERGE", "Merge PDF"),
                    ("PDF_SPLIT", "Split PDF"),
                    ("PDF_ROTATE", "Rotate PDF"),
                    ("PDF_TO_IMAGES", "PDF to Images"),
                    ("IMAGES_TO_PDF", "Images to PDF"),
                    ("IMAGE_CONVERT", "Convert Image"),
                    ("IMAGE_RESIZE", "Resize Image"),
                    ("IMAGE_COMPRESS", "Compress Image"),
                    ("IMAGE_ROTATE_FLIP", "Rotate or Flip Image"),
                ],
                max_length=50,
            ),
        ),
    ]
